### Home
GET http://localhost:1234

### Docs
GET http://localhost:1234/docs

### Not Found
GET http://localhost:1234/kadhwuikdw

/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////

### GET all Movies
GET http://localhost:1234/movies

### GET Movies with genre
GET http://localhost:1234/movies?genre=Sci-Fi&year=2010&lang=es

### GET Movie by ID
GET http://localhost:1234/movies/ebe60bf9-ca29-4d6d-9b2f-5fbe3eafc9ab?lang=es

### POST Movie
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Peli prueba",
  "description": "asdasd",
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJR_cyT0wMJLZILBMx9MpHSf8XjDfkckvSQ&usqp=CAU",
  "genre": [
    "Action",
    "Drama"
  ],
  "rate": 1.1
}

### PUT Movie by ID
PUT http://localhost:1234/movies/ebe60bf9-ca29-4d6d-9b2f-5fbe3eafc9ab
Content-Type: application/json

{
  "title": "Peli prueba",
  "description": "asdasd",
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJR_cyT0wMJLZILBMx9MpHSf8XjDfkckvSQ&usqp=CAU",
  "genre": [
    "Action",
    "Drama"
  ],
  "rate": 1.1
}

### PATCH Movie by ID
PATCH http://localhost:1234/movies/ebe60bf9-ca29-4d6d-9b2f-5fbe3eafc9ab
Content-Type: application/json

{
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "rate": 1.1
}

### DELETE Movie by ID
DELETE http://localhost:1234/movies/ebe60bf9-ca29-4d6d-9b2f-5fbe3eafc9ab

/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////

### GET all Movies
GET http://localhost:1234/series

### GET Movies with genre
GET http://localhost:1234/series?genre=comedy&year=2010&lang=es

### GET Movie by ID
GET http://localhost:1234/series/be61f804-8f37-4086-8da1-00693b630086?lang=en

### POST Movie
POST http://localhost:1234/series
Content-Type: application/json

{
  "title": "Peli prueba",
  "description": "asdasd",
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJR_cyT0wMJLZILBMx9MpHSf8XjDfkckvSQ&usqp=CAU",
  "genre": [
    "Action",
    "Drama"
  ],
  "rate": 1.1
}

### PUT Movie by ID
PUT http://localhost:1234/series/be61f804-8f37-4086-8da1-00693b630086
Content-Type: application/json

{
  "title": "Peli prueba",
  "description": "asdasd",
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJR_cyT0wMJLZILBMx9MpHSf8XjDfkckvSQ&usqp=CAU",
  "genre": [
    "Action",
    "Drama"
  ],
  "rate": 1.1
}

### PATCH Movie by ID
PATCH http://localhost:1234/series/be61f804-8f37-4086-8da1-00693b630086
Content-Type: application/json

{
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "rate": 1.1
}

### DELETE Movie by ID
DELETE http://localhost:1234/series/be61f804-8f37-4086-8da1-00693b630086
