### Home
GET http://localhost:1234

### Docs
GET http://localhost:1234/docs

### Not Found
GET http://localhost:1234/kadhwuikdw

/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////

### GET all Movies
GET http://localhost:1234/movies

### GET Movies with genre
GET http://localhost:1234/movies?lang=es&offset=11&limit=12

### GET Movie by ID
GET http://localhost:1234/movies/ebe60bf9-ca29-4d6d-9b2f-5fbe3eafc9ab?lang=es

### POST Movie
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Peli prueba",
  "description": "asdasd",
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJR_cyT0wMJLZILBMx9MpHSf8XjDfkckvSQ&usqp=CAU",
  "genre": [
    "Action",
    "Drama"
  ],
  "rate": 1.1
}

### PUT Movie by ID
PUT http://localhost:1234/movies/ebe60bf9-ca29-4d6d-9b2f-5fbe3eafc9ab
Content-Type: application/json

{
  "title": "Peli prueba",
  "description": "asdasd",
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJR_cyT0wMJLZILBMx9MpHSf8XjDfkckvSQ&usqp=CAU",
  "genre": [
    "Action",
    "Drama"
  ],
  "rate": 1.1
}

### PATCH Movie by ID
PATCH http://localhost:1234/movies/ebe60bf9-ca29-4d6d-9b2f-5fbe3eafc9ab
Content-Type: application/json

{
  "year": 1234,
  "director": "YO",
  "duration": 1,
  "rate": 1.1
}

### DELETE Movie by ID
DELETE http://localhost:1234/movies/ebe60bf9-ca29-4d6d-9b2f-5fbe3eafc9ab

/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////

### GET all Movies
GET http://localhost:1234/series

### GET Movies with genre
GET http://localhost:1234/series?lang=es&offset=3&limit=2

### GET Movie by ID
GET http://localhost:1234/series/be61f804-8f37-4086-8da1-00693b630086?lang=en

### POST Movie
POST http://localhost:1234/series
Content-Type: application/json

{
  "title": "Serie prueba",
  "description": "asdasd",
  "started": 1234,
  "ended": 4444,
  "seasons": 1,
  "episodes": 44,
  "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJR_cyT0wMJLZILBMx9MpHSf8XjDfkckvSQ&usqp=CAU",
  "genre": [
    "Action",
    "Drama"
  ],
  "rate": 1.1
}

### PUT Movie by ID
PUT http://localhost:1234/series/be61f804-8f37-4086-8da1-00693b630086
Content-Type: application/json

{
  "title": "Serie prueba",
  "description": "asdasd",
  "started": 1234,
  "ended": 4444,
  "seasons": 1,
  "episodes": 44,
  "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmJR_cyT0wMJLZILBMx9MpHSf8XjDfkckvSQ&usqp=CAU",
  "genre": [
    "Action",
    "Drama"
  ],
  "rate": 1.1
}


### PATCH Movie by ID
PATCH http://localhost:1234/series/be61f804-8f37-4086-8da1-00693b630086
Content-Type: application/json

{
  "year": 1234,
  "diasd": "asd",
  "daasdasd": 123,
  "genre": ["asd", 132]
}

### DELETE Movie by ID
DELETE http://localhost:1234/series/be61f804-8f37-4086-8da1-00693b630086

/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////

### GET all Quotes
GET http://localhost:1234/quotes

### GET Quotes with genre
GET http://localhost:1234/quotes?category=motivation&lang=es&offset=3&limit=2

### GET Quote by ID
GET http://localhost:1234/quotes/440bcfeb-2a06-4fd2-a4ef-2107636b6e96?lang=es

### POST Quote
POST http://localhost:1234/quotes
Content-Type: application/json

{
  "text": "Cita prueba",
  "author": "asdasd",
  "category": [
    "asd",
    "dasdas"
  ]
}

### PUT Quote by ID
PUT http://localhost:1234/quotes/440bcfeb-2a06-4fd2-a4ef-2107636b6e96
Content-Type: application/json

{
  "text": "Cita prueba",
  "author": "asdasd",
  "category": [
    "asd",
    "dasdas"
  ]
}


### PATCH Quote by ID
PATCH http://localhost:1234/quotes/440bcfeb-2a06-4fd2-a4ef-2107636b6e96
Content-Type: application/json

{
  "text": "Cita prueba",
  "author": "asdasd"
}

### DELETE Quote by ID
DELETE http://localhost:1234/quotes/440bcfeb-2a06-4fd2-a4ef-2107636b6e96

/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////
/////////////////////

### GET all Quotes
GET http://localhost:1234/books

### GET Quotes with genre
GET http://localhost:1234/books?author=Jane&lang=es&offset=3&limit=2

### GET Quote by ID
GET http://localhost:1234/books/67a6301c-e9ee-432e-8f1a-d48f1d03f89b?lang=es

### POST Quote
POST http://localhost:1234/books
Content-Type: application/json

{
  "title": "Cita prueba",
  "description": "asdasd",
  "year": 123,
  "author": "a",
  "img": "asd",
  "genre": [
    "asd",
    "dasdas"
  ]
}

### PUT Quote by ID
PUT http://localhost:1234/books/67a6301c-e9ee-432e-8f1a-d48f1d03f89b
Content-Type: application/json

{
  "title": "Cita prueba",
  "description": "asdasd",
  "year": 123,
  "author": "a",
  "img": "asd",
  "genre": [
    "asd",
    "dasdas"
  ]
}


### PATCH Quote by ID
PATCH http://localhost:1234/books/67a6301c-e9ee-432e-8f1a-d48f1d03f89b
Content-Type: application/json

{
  "author": "asdasd"
}

### DELETE Quote by ID
DELETE http://localhost:1234/books/67a6301c-e9ee-432e-8f1a-d48f1d03f89b
